### ISSUE TITLE
Microsoft auth occasionally fails. Sign-in button disappears but server list doesn't appear.

### ISSUE THREAD

**Issue by Jaxkr** [NFT-Worlds/NFT-Worlds-Game-Client#10]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/1147244/163498277-09496279-6cab-40bb-96f4-45bc515e7ea8.png">

**Comment by shibalanz** [comment]
<img width="1275" alt="Screenshot 2022-04-15 at 10 49 45 AM" src="https://user-images.githubusercontent.com/103706335/163501161-83d991fb-7531-42b0-b46e-8bddee1f94c5.png">

**Comment by shibalanz** [comment]
I see the 'security token' message, which then disappears and I'm back to the Sign in with Microsoft link

**Comment by shibalanz** [comment]
Ah, just checked the console errors: Error: Error invoking remote method 'auth:login': Error: The account doesn't have an Xbox account.

This is true - I do not have an Xbox account.
