### ISSUE TITLE
Launching Minecraft with shaders enabled causes Minecraft to crash on load

### ISSUE THREAD

**Issue by lunarraid** [NFT-Worlds/NFT-Worlds-Game-Client#12]
I am on a m1x Macbook Pro. The launcher loaded, showed all the worlds, and downloaded Minecraft just fine. If I attempt to launch the Mothership, the Minecraft client will open and the loading bar will load to the end. Upon reaching the end, the client will crash. If I go into settings and disable shaders, however, it will load correctly.

**Comment by Jaxkr** [comment]
Thanks for your report, we'll disable shaders by default on M1 Macs in the next release.

**Comment by lunarraid** [comment]
Is there an open ticket for making shaders work on m1?
