### ISSUE TITLE
Your NFT Worlds account is being set up. Please wait... 

### ISSUE THREAD

**Issue by RonsTop01** [NFT-Worlds/NFT-Worlds-Game-Client#19]
I downloaded and installed nft worlds already, but after I signed in in Microsoft account, it shows 'Your NFT Worlds account is being set up. Please wait....'. I waited for a long time but nothing happened. 
![image](https://user-images.githubusercontent.com/104243272/164873942-8b9b641b-ad85-481d-80cf-2cb2817e8397.png)

**Comment by Jaxkr** [comment]
This has been fixed on the API end, thanks for you report! :)
