### ISSUE TITLE
Stuck at "Your NFT Worlds account is being set up. Please wait..."

### ISSUE THREAD

**Issue by MrPapi420blazeit** [NFT-Worlds/NFT-Worlds-Game-Client#6]
Unsure if there are prerequisites to loading this (in terms of Minecraft or versions). I have both clients on my PC. I'm on Windows 11 (updated yesterday).  

Minecraft versions 1.18.1201.0 and Java 1.0.159.0

Its been about 10 minutes and still not loading.

**Comment by Jaxkr** [comment]
Thanks for the report. We'll look into getting this fixed ASAP.

**Comment by anymose96** [comment]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/80447029/163665993-309506d6-6daa-4ba6-917f-8a0bde9169f6.png">
yep same error
account have bought MC linked

**Comment by Jaxkr** [comment]
This has been resolved. Thanks for your report.
